language: node_js
node_js:
 - 7
cache:
 directories:
   - node_modules
script:
 - npm run build
 - npm test -- --coverage && cat ./coverage/lcov.info | coveralls
notifications:
  email: false
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local-dir: build
  on:
    branch: master